# Generated by Django 5.2.5 on 2025-08-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileUrl',
        ),
    ]
