# Generated by Django 5.2.5 on 2025-09-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_album_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
