# Generated by Django 5.2.5 on 2025-09-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_album_album_name_alter_photo_photo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='resolution',
            field=models.CharField(max_length=20),
        ),
    ]
