# Generated by Django 5.2.5 on 2025-09-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_photo_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='resolution',
            field=models.CharField(max_length=19),
        ),
    ]
